-- Создаём таблицу airport
CREATE TABLE IF NOT EXISTS airport (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iata_code TEXT NOT NULL,
    name TEXT NOT NULL,
    passengers INTEGER
);

-- Вставляем 100 записей (аэропортов)
INSERT INTO airport (iata_code, name, passengers) VALUES ('ATL', 'Hartsfield-Jackson Atlanta International Airport', 108067766);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DXB', 'Dubai International Airport', 92300000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DFW', 'Dallas/Fort Worth International Airport', 87817864);
INSERT INTO airport (iata_code, name, passengers) VALUES ('HND', 'Tokyo Haneda Airport', 85000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LHR', 'London Heathrow Airport', 83882140);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DEN', 'Denver International Airport', 82358744);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ORD', 'O''Hare International Airport', 80043050);
INSERT INTO airport (iata_code, name, passengers) VALUES ('IST', 'Istanbul Airport', 79988272);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DEL', 'Indira Gandhi International Airport', 77820834);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PVG', 'Shanghai Pudong International Airport', 76787039);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LAX', 'Los Angeles International Airport', 76587980);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CAN', 'Guangzhou Baiyun International Airport', 76364767);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ICN', 'Seoul Incheon International Airport', 70669246);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CDG', 'Charles de Gaulle Airport', 70290260);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SIN', 'Singapore Changi Airport', 67700000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('AMS', 'Amsterdam Airport Schiphol', 61882546);
INSERT INTO airport (iata_code, name, passengers) VALUES ('FRA', 'Frankfurt Airport', 54089293);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MUC', 'Munich Airport', 48400000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('IAD', 'Washington Dulles International Airport', 47000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('JFK', 'John F. Kennedy International Airport', 46000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MEX', 'Mexico City International Airport', 45000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SYD', 'Sydney Kingsford Smith Airport', 43000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MEL', 'Melbourne Airport', 42000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('GRU', 'São Paulo–Guarulhos International Airport', 40000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('EZE', 'Ministro Pistarini International Airport, Buenos Aires', 39000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International Airport, Mumbai', 38000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CGK', 'Soekarno–Hatta International Airport, Jakarta', 37000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PEK', 'Beijing Capital International Airport', 36000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('KUL', 'Kuala Lumpur International Airport', 35000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BKK', 'Suvarnabhumi Airport, Bangkok', 34000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SVO', 'Sheremetyevo International Airport, Moscow', 33000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CAI', 'Cairo International Airport', 32000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MNL', 'Ninoy Aquino International Airport, Manila', 31000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('HKG', 'Hong Kong International Airport', 30000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('TPE', 'Taiwan Taoyuan International Airport', 29000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DOH', 'Hamad International Airport, Doha', 28000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('RUH', 'King Khalid International Airport, Riyadh', 27000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DUB', 'Dublin Airport', 26000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LIS', 'Lisbon Humberto Delgado Airport', 25000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('OSL', 'Oslo Gardermoen Airport', 24000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ZRH', 'Zurich Airport', 23000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BER', 'Berlin Brandenburg Airport', 22000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DUS', 'Düsseldorf Airport', 21000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('HAM', 'Hamburg Airport', 20000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BRU', 'Brussels Airport', 19000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CPH', 'Copenhagen Airport', 18000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('VIE', 'Vienna International Airport', 17000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MAN', 'Manchester Airport', 16000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LPL', 'Liverpool John Lennon Airport', 15000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BHX', 'Birmingham Airport', 14000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('STN', 'London Stansted Airport', 13000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LTN', 'London Luton Airport', 12000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 70300000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('FCO', 'Rome–Fiumicino International Airport', 50000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ARN', 'Stockholm Arlanda Airport', 28000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('RIX', 'Riga International Airport', 10000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PRG', 'Václav Havel Airport Prague', 12000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BUD', 'Budapest Ferenc Liszt International Airport', 11000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DME', 'Domodedovo International Airport, Moscow', 29000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('VKO', 'Vnukovo International Airport, Moscow', 25000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LED', 'Pulkovo Airport, St. Petersburg', 15000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('HEL', 'Helsinki-Vantaa Airport', 16000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('GVA', 'Geneva Airport', 13000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ZAG', 'Zagreb Airport', 5000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('VNO', 'Vilnius International Airport', 7000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('TLL', 'Tallinn Airport', 6000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MXP', 'Milan Malpensa Airport', 32000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('NAP', 'Naples International Airport', 8000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BSL', 'EuroAirport Basel-Mulhouse-Freiburg', 9000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LJU', 'Ljubljana Jože Pučnik Airport', 4000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('TGD', 'Podgorica Airport', 3000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BEG', 'Belgrade Nikola Tesla Airport', 15000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SOF', 'Sofia Airport', 12000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('ATH', 'Athens International Airport', 25000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MLA', 'Malta International Airport', 7000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('FLL', 'Fort Lauderdale-Hollywood International Airport', 26000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('DTW', 'Detroit Metropolitan Wayne County Airport', 34000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PHL', 'Philadelphia International Airport', 40000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SEA', 'Seattle-Tacoma International Airport', 40000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CLT', 'Charlotte Douglas International Airport', 46000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PHX', 'Phoenix Sky Harbor International Airport', 37000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SAN', 'San Diego International Airport', 25000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('IAH', 'George Bush Intercontinental Airport, Houston', 45000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BOS', 'Boston Logan International Airport', 23000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MSP', 'Minneapolis–Saint Paul International Airport', 28000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SLC', 'Salt Lake City International Airport', 15000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('MCO', 'Orlando International Airport', 50000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('LAS', 'McCarran International Airport, Las Vegas', 50000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 24000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('RDU', 'Raleigh–Durham International Airport', 15000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SJC', 'San Jose International Airport', 17000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('OAK', 'Oakland International Airport', 11000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SMF', 'Sacramento International Airport', 11500000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('PIT', 'Pittsburgh International Airport', 13000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('YVR', 'Vancouver International Airport', 25000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('YYZ', 'Toronto Pearson International Airport', 43000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('SCL', 'Comodoro Arturo Merino Benítez International Airport, Santiago', 19000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('BOG', 'El Dorado International Airport, Bogotá', 27000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('CMB', 'Bandaranaike International Airport, Colombo', 12000000);
INSERT INTO airport (iata_code, name, passengers) VALUES ('KBP', 'Boryspil International Airport, Kyiv', 22000000);